### ISSUE TITLE
undefined method Doku_Handler::addCall

### ISSUE THREAD

**Issue by ezbik** [dokufreaks/plugin-folded#85]
Dokuwiki text that throws an exception:

```
++++ title|
text
++++
```

Dokuwiki text that works well (???)

```

++++ Title |

| This table | is only shown | when you unfold the block |

{{page>some other wiki page&inline}}

++++
```

The exception

```
Oct 15 13:58:57 pathos php[3843091]: PHP Fatal error:  Uncaught Error: Call to undefined method Doku_Handler::addCall() in /var/lib/dokuwiki/lib/plugins/folded/syntax/div.php:32
Oct 15 13:58:57 pathos php[3843091]: Stack trace:
Oct 15 13:58:57 pathos php[3843091]: #0 /usr/share/dokuwiki/inc/parser/handler.php(95): syntax_plugin_folded_div->handle()
Oct 15 13:58:57 pathos php[3843091]: #1 /usr/share/dokuwiki/inc/parser/lexer.php(526): Doku_Handler->plugin()
Oct 15 13:58:57 pathos php[3843091]: #2 /usr/share/dokuwiki/inc/parser/lexer.php(443): Doku_Lexer->_invokeParser()
Oct 15 13:58:57 pathos php[3843091]: #3 /usr/share/dokuwiki/inc/parser/lexer.php(411): Doku_Lexer->_dispatchTokens()
Oct 15 13:58:57 pathos php[3843091]: #4 /usr/share/dokuwiki/inc/parser/parser.php(123): Doku_Lexer->parse()
Oct 15 13:58:57 pathos php[3843091]: #5 /usr/share/dokuwiki/inc/parserutils.php(207): Doku_Parser->parse()
Oct 15 13:58:57 pathos php[3843091]: #6 /usr/share/dokuwiki/inc/parserutils.php(169): p_get_instructions()
Oct 15 13:58:57 pathos php[3843091]: #7 /usr/share/dokuwiki/inc/parserutils.php(482): p_cached_instructions()
Oct 15 13:58:57 pathos php[3843091]: #8 /usr/share/dokuwiki/inc/parserutils.php(272): p_render_metadata()
Oct 15 13:58:57 pathos php[3843091]: #9 /usr/share/dokuwiki/inc/common.php(251): p_get_metadata()
Oct 15 13:58:57 pathos php[3843091]: #10 /usr/share/dokuwiki/doku.php(91): pageinfo()
Oct 15 13:58:57 pathos php[3843091]: #11 {main}
Oct 15 13:58:57 pathos php[3843091]:   thrown in /var/lib/dokuwiki/lib/plugins/folded/syntax/div.php on line 32

```

LAMP ubuntu 22.04 PHP 7.4.3-4ubuntu2.19.

**Comment by ezbik** [comment]
these are working too:

3 dots:

```
++++ title |
... 
++++
```

6 dots:

```
++++ title |
......
++++
```

Other number of dots throw 500 errors.

**Comment by Klap-in** [comment]
Which version of DokuWiki are you using?

**Comment by ezbik** [comment]
Ubuntu's   dokuwiki       0.0.20180422.a-2

**Comment by Klap-in** [comment]
The next version of 2020 has replaced the _addCall() by addCall(). Please update at least to that version for this case, but if you like to use recent version of plugins in general, it is better to update to the most recent version of DokuWiki (Jack Jackrum 2023 release). Unfortunately, the Debian/Ubuntu packages of DokuWiki delay often significantly. So better you use a recent version from DokuWiki's download page. If you prefer using the version from the package manager, you have to use php versions and plugins versions which match that version.

**Comment by ezbik** [comment]
Thank you for the response. Indeed fresh Dokuwiki installation fixed the issue.
